
name: Portfolio Deployment on s3

on:
  push:
    branches:
      - master
      
jobs:
    build-test-and-deploy:
      runs-on: ubuntu latest
      steps:
        - name: Checkout
          uses: action/checkout@v1
          
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Deploymet of friends portfolio site .
          run: aws s3 sync . s3://dep-gitaction-s3-bucket --delete
